// supabase/functions/send-invite-email/index.ts
// Creates an invite_tokens record and sends a robot sharing invitation email
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { sendEmail } from '../_shared/resend.ts';
import { logEmail } from '../_shared/logger.ts';
import { checkRateLimit } from '../_shared/rate-limiter.ts';
import { baseTemplate, escapeHtml, FOOTER } from '../_shared/templates.ts';

const CORS = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
    if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS });

    try {
        const { robotId, inviteeEmail, role = 'viewer' } = await req.json() as {
            robotId: string;
            inviteeEmail: string;
            role?: 'viewer' | 'operator' | 'admin';
        };

        if (!robotId || !inviteeEmail) {
            return json({ error: 'robotId and inviteeEmail are required' }, 400);
        }

        // Validate caller is authenticated
        const authHeader = req.headers.get('Authorization') ?? '';
        const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
        const anonKey     = Deno.env.get('SUPABASE_ANON_KEY')!;
        const serviceKey  = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

        const callerClient = createClient(supabaseUrl, anonKey, {
            global: { headers: { Authorization: authHeader } },
            auth: { autoRefreshToken: false, persistSession: false },
        });
        const { data: { user: caller } } = await callerClient.auth.getUser();
        if (!caller) return json({ error: 'Unauthorized' }, 401);

        const supabase = createClient(supabaseUrl, serviceKey, {
            auth: { autoRefreshToken: false, persistSession: false },
        });

        // Verify caller owns the robot
        const { data: robot, error: robotErr } = await supabase
            .from('robots')
            .select('id, name, user_id')
            .eq('id', robotId)
            .eq('user_id', caller.id)
            .single();

        if (robotErr || !robot) return json({ error: 'Robot not found or access denied' }, 403);

        // Rate limit invitations per inviter
        const allowed = await checkRateLimit(caller.id, 'invite');
        if (!allowed) return json({ error: 'Rate limit reached', code: 'RATE_LIMITED' }, 429);

        // Create invite token (token generated by DB default)
        const { data: invite, error: inviteErr } = await supabase
            .from('invite_tokens')
            .insert({
                robot_id:      robotId,
                inviter_id:    caller.id,
                invitee_email: inviteeEmail,
                role,
            })
            .select('token, expires_at')
            .single();

        if (inviteErr || !invite) {
            console.error('[send-invite-email] Failed to create invite:', inviteErr?.message);
            return json({ error: 'Failed to create invite token' }, 500);
        }

        const inviterName = escapeHtml((caller.user_metadata?.full_name ?? caller.email?.split('@')[0] ?? 'Someone').split(' ')[0]);
        const robotName   = escapeHtml(robot.name ?? 'a cleaning robot');
        const roleLabel   = role.charAt(0).toUpperCase() + role.slice(1);
        const deepLink    = `smartcleanerpro://accept-invite?token=${invite.token}&robot_id=${robotId}`;

        const html = buildInviteHtml(inviterName, robotName, roleLabel, invite.token, deepLink);

        const result = await sendEmail({
            to:      inviteeEmail,
            subject: `${inviterName} invited you to control ${robotName}`,
            html,
        });

        await logEmail({
            userId:       caller.id,
            emailType:    'invite',
            recipient:    inviteeEmail,
            status:       result.success ? 'sent' : 'failed',
            resendId:     result.id,
            errorMessage: result.error,
            metadata:     { robotId, role, inviteToken: invite.token },
        });

        if (!result.success) return json({ error: result.error, code: 'EMAIL_FAILED' }, 500);

        return json({ success: true, token: invite.token });

    } catch (err: any) {
        console.error('[send-invite-email] Unexpected error:', err.message);
        return json({ error: err.message ?? 'Unexpected error' }, 500);
    }
});

function buildInviteHtml(inviterName: string, robotName: string, role: string, token: string, deepLink: string): string {
    return baseTemplate(`
  <div class="hdr purple">
    <h1>Smart Cleaner Pro</h1>
    <p>Robot sharing invitation</p>
  </div>
  <div class="body">
    <h2>You've Been Invited! 🤖</h2>
    <p><strong>${inviterName}</strong> has invited you to access <strong>${robotName}</strong> as a <strong>${role}</strong>.</p>
    <div class="info-box" style="margin-top:20px">
      As a <strong>${role}</strong>, you'll be able to:
      <ul style="margin-top:10px">
        ${role === 'Admin'
            ? '<li>Full control — start, stop, schedule, and manage settings</li><li>Invite and remove other members</li>'
            : role === 'Operator'
                ? '<li>Start and stop cleaning sessions</li><li>View cleaning history and reports</li>'
                : '<li>View live robot status and cleaning history</li>'}
      </ul>
    </div>
    <div style="text-align:center">
      <a href="${deepLink}" class="btn" style="background:#8B5CF6">Accept Invitation</a>
    </div>
    <hr class="divider"/>
    <p class="note">
      ⏱ This invitation expires in <strong>7 days</strong>. If you don't have the app yet,
      download Smart Cleaner Pro and the invitation will be waiting for you.
    </p>
    <p class="note" style="margin-top:12px">If the button doesn't work, open the app and enter this token manually:</p>
    <div class="link-box">${escapeHtml(token)}</div>
    <p class="note" style="margin-top:16px">If you didn't expect this invitation, you can safely ignore this email.</p>
  </div>
  ${FOOTER}`);
}

function json(body: unknown, status = 200) {
    return new Response(JSON.stringify(body), {
        status,
        headers: { ...CORS, 'Content-Type': 'application/json' },
    });
}
